# _config.yml

title: JR Field Notes
description: The random musings of an insane person 
author:
  name: Jarrod Rose

remote_theme: "jekyll/minima"

minima:
  nav_pages:
    - about.md
  show_excerpts: true
  hide_site_feed_link: false
  date_format: "%e %B %Y"
  social_links:
    - title: Instagram - @jarrodrose
      icon: instagram
      url: "https://www.instagram.com/jarrodrose/"
    - title: Mastodon - mastodon.social/@jarrodrose
      icon: mastodon
      url: "https://mastodon.social/@jarrodrose"
    - title: Youtube - @jarrodrose
      icon: youtube
      url: "https://www.youtube.com/@jarrodrose"
    - title: GitHub - jarrodrose
      icon: github
      url: "https://github.com/jarrodrose"
